[package]
name = "amazon-sqs-pg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
aws-config = { version = "1.5.6", features = ["behavior-version-latest"] }
aws-sdk-sqs = "1.43.0"
dotenvy = "0.15.7"
tokio = { version = "1.40.0", features = ["full"] }
